default: &default
  adapter: sqlite3
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000  # Increased from default 5000ms to give more time for locks to clear
  busy_timeout: 5000  # Add explicit busy_timeout to wait for locks

# Keep SQLite for development
development:
  <<: *default
  database: storage/development.sqlite3

# Keep SQLite for test
test:
  <<: *default
  database: storage/test.sqlite3

# Use PostgreSQL only in production
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
