default: &default
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

# Keep SQLite for development
development:
  <<: *default
  adapter: sqlite3
  database: storage/development.sqlite3

# Keep SQLite for test
test:
  <<: *default
  adapter: sqlite3
  database: storage/test.sqlite3

# Use PostgreSQL only in production
production:
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  url: <%= ENV['DATABASE_URL'] %>
