interests:
  creativity:
    - Problem Solving
    - Critical Thinking
    - Innovation
    - Design Thinking
    - Storytelling
    - Visual Expression
    - Creative Writing
  exploration:
    - Adventure
    - Discovery
    - Nature
    - Space
    - Ocean
    - Travel
    - Exploration
  technology:
    - Gaming
    - Digital Creation
    - Animation
    - Robotics
    - Virtual Reality
    - Social Media
  lifestyle:
    - Sports
    - Music
    - Dance
    - Photography
    - Cooking
    - Fashion
    - Entertainment
  personal_growth:
    - Leadership
    - Teamwork
    - Communication
    - Self Expression
    - Goal Setting
    - Personal Development
  social_impact:
    - Environment
    - Community
    - Social Justice
    - Sustainability
    - Cultural Exchange
    - Global Issues
